.TH cowspeak 1 "29th Oct 2018" "1.4" "cowspeak man page"
.SH NAME
cowspeak \- Display an animal with a random quote or your own text.
.SH SYNOPSIS
cowspeak, the program displays an animal with a random quote or your own text.
.SH OPTIONS

.SH		--art or -a
		Display a tutorial on adding your own art.

.SH		--blink or -b
		Blink the texts (not supported in all terminals yet).

.SH		--documentation or -d
		Display the whole documentation including this help.

.SH		--file= or -f=
		Specify the ASCII file path to display your own ASCII art.

.SH		--fortune
		Show a fortune without any art.

.SH		--help or -h
		Display this help.

.SH		--manual or -m
		Display a manual. Same as documentation.

.SH		--read or -r=
		Read a file.

.SH		--text= or -t=
		Display a custom text.

.SH		--update or -u
		Update fortune database from Github.

.SH AUTHOR
Sourav Goswami (souravgoswami@protonmail.com)
