.TH cowspeak 1 "29th Oct 2018" "1.2" "cowspeak man page"
.SH NAME
cowspeak \- Display an animal with a random quote or your own text.
.SH SYNOPSIS
cowspeak, the program displays an animal with a random quote or your own text.
.SH OPTIONS
--text= or -t=		Display a custom text.

--read or -r=		Read a file.

--file= or -f=		Specify the ASCII file path to display your own ASCII art.

--help or -h		Display this help.

--documentation or -d	Display the whole documentation including this help.

--art or -a		Display a tutorial on adding your own art.

--update or -u		Update fortune database from Github.
.SH AUTHOR
Sourav Goswami (souravgoswami@protonmail.com)
